networks:
  traffic_devils:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - traffic_devils

  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER", "--quiet" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    networks:
      - traffic_devils

  api:
    build:
      context: .
    container_name: api
    ports:
      - "${API_PORT}:8000"
    command: /bin/sh -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traffic_devils
