"""Initial tables

Revision ID: b795e1098284
Revises: 
Create Date: 2024-12-11 16:50:38.250720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b795e1098284'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('tg_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("INSERT INTO roles (name) VALUES ('admin');")
    op.execute("INSERT INTO roles (name) VALUES ('manager');")
    op.execute("INSERT INTO roles (name) VALUES ('user');")

    op.execute("INSERT INTO users (username, password, registered_at, role_id) VALUES ('admin', '$2b$12$mtjBwlKHHKNIn0xHHwujyuqD29wt.mCBJ8JOtSWw6AYdl22pKBVTy', '2024-12-11 18:07:48.815880', 1);")
    op.execute("INSERT INTO users (username, password, registered_at, role_id) VALUES ('manager', '$2b$12$mtjBwlKHHKNIn0xHHwujyuqD29wt.mCBJ8JOtSWw6AYdl22pKBVTy', '2024-12-11 18:07:48.815880', 2);")
    op.execute("INSERT INTO users (username, password, registered_at, role_id, manager_id) VALUES ('user', '$2b$12$mtjBwlKHHKNIn0xHHwujyuqD29wt.mCBJ8JOtSWw6AYdl22pKBVTy', '2024-12-11 18:07:48.815880', 3, 2);")
    op.execute("INSERT INTO users (username, password, registered_at, role_id) VALUES ('another_user', '$2b$12$mtjBwlKHHKNIn0xHHwujyuqD29wt.mCBJ8JOtSWw6AYdl22pKBVTy', '2024-12-11 18:07:48.815880', 3);")


    op.execute("""INSERT INTO messages (bot_token, chat_id, message, tg_response, author_id, created_at) VALUES ('string', 'string', 'string', '{"ok": false, "error_code": 404, "description": "Not Found"}', 3, '2024-12-11 19:27:36.546658')""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('auth_tokens')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
